ARG FULL_TAG=latest
FROM apluslms/grade-nodejs:$FULL_TAG

ENV NODE_PATH /usr/lib/node_modules/globals/node_modules/

ADD zombie/ /

RUN (cd /root && npm install -g) \
 && apt_install python3 python3-pip \
 && pip3 install --no-cache-dir --disable-pip-version-check html5lib \
 && find /usr/local/lib/python* -type d -regex '.*/locale/[a-z_A-Z]+' -not -regex '.*/\(en\|fi\|sv\)' -print0 | xargs -0 rm -rf \
 && find /usr/local/lib/python* -type d -name 'tests' -print0 | xargs -0 rm -rf
